# Start by building the application.
FROM golang:1.17 as build
WORKDIR /app
ADD . /app
RUN go get -d -v ./...
RUN go build -o demo

# Now copy it into our base image.
FROM gcr.io/distroless/base-debian11
COPY --from=build /app /
CMD ["./demo"]

# Output is docker run -ti my__image --> # hello world using go:linkname!